<?php

namespace CoreBundle\Repository;

/**
 * InfosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfosRepository extends \Doctrine\ORM\EntityRepository
{
}
